---
title: "results_3_field"
author: "Elizabeth Williams"
date: "2024-08-15"
output: html_document
---

## Load Packages

```{r load packages, message = FALSE}
library(revtools)
library(synthesisr)
library(dplyr)
library(janitor)
library(tidyverse)
library(stringr)
library(tidytext)
library(widyr)
library(ggraph)
library(ggplot2)
library(maps)
library(igraph)
library(base)
library(stm)
library(wordcloud)
library(sf) #vector package
library(terra) #raster package
library(ggbreak)
library(UpSetR)
```

## Add Functions
```{r add functions}
convert_to_TF <- function(x) {
  return(grepl("TRUE", x, ignore.case = TRUE))
}

check_partial_terms <- function(input_column, key_terms) {
  sapply(input_column, function(x) any(sapply(key_terms, function(term) grepl(term, x, ignore.case = TRUE))))
}

check_full_terms <- function(input_column, key_terms) {
  pattern <- paste0("\\b(", paste(key_terms, collapse = "|"), ")\\b")
  str_detect(input_column, regex(pattern, ignore_case = TRUE))
}

```

## Import data
```{r load data, message = FALSE}
#import remote sensing papers
field_data <- read.csv("data_working/field_data.csv")

```


## Quick Field Stats
```{r quick field stats}

table(field_data$bio.exp)
table(field_data$structural)
table(field_data$slip_driver)

```

## Number of slips surveyed
```{r number of slips surveyed}

# NUMBER OF SLIPS
table(field_data$slip_number)
field_data <- field_data %>%
  mutate(slip_number = str_replace(slip_number, "MISSING", "NA"))

field_data$slip_number <- as.numeric(field_data$slip_number)

table(field_data$slip_number)
summary(field_data$slip_number)

#histogram
ggplot(field_data, aes(x = slip_number)) +
  geom_histogram(binwidth = 1, fill = "grey", color = "black", na.rm = TRUE) +
  labs(title = "Landslides Surveyed in Field Studies",
       x = "# Landslides Surveyed",
       y = "Studies") +
  theme_minimal()

```


## General T/F results
```{r clean T/F results}

#create temporary list of columns to be made to TRUE/FALSE
tmp_field_convert <- c("veg_trait", "veg_spp", "int_plant_plant", "int_plant_other", "int_plant_prop", "time",
                       "compare_veg", "seeds", "exotic")

# make listed columns T/F
for (col in tmp_field_convert) {
  field_data[[paste0(col, "_TF")]] <- convert_to_TF(field_data[[col]])
}

```

``` {r interactions with landslide properties}
field_int_prop <- field_data %>%
  mutate(int_plant_prop = str_replace(int_plant_prop, "TRUE - ", "")) %>%
  separate_rows(int_plant_prop, sep = ", ")

table(field_int_prop$int_plant_prop)

groups_field_prop <- list(
  prop_topo = c("slope", "aspect", "elevation", "curvature", "hillshade"),
  prop_weather = c("temperature", "precipitation", "light", "solar radiation"),
  prop_size = c("slip size", "slip area", "length", "width"),
  prop_seed_src = c("edge proximity", "snag cover", "native forest proximity", "bird perches", 
                    "seed source proximity", "isolation", "remnant vegetation"),
  prop_disturb_prox = c("road proximity", "stream proximity", "gorge proximity"),
  prop_prior_disturb = c("prior burning", "prior clearing", "prior human disturbance", "disturbance history"),
  prop_zone = c("zone", "distance from top", "distance from base"),
  prop_soil_chem = c("nitrogen", "phosphorus", "carbon", "aluminium", "potassium", "calcium", "copper", "iron", 
                     "magnesium", "manganese", "zinc", "salt", "sodium", "fertilizer", "nutrients", "nitrate", 
                     "al/ca ratio", "cation exchange capacity", "cation content", "soil fertility", "microbial biomass", 
                     "dehydrogenase activity", "organic matter", "organic layer depth", "pH", "water quality"),
  prop_soil_phys = c("soil texture", "coarse fraction", "grain size", "clast size", "clast shape", "soil depth", 
                     "deposit depth", "bulk density", "soil type", "soil temp", "stone cover", "stone diameter", 
                     "microsites", "debris cover", "soil toughness", "soil resistance", "bare soil cover", "roughness",
                     "litter", "soil moisture", "available water content", "water holding capacity", "parent material", 
                     "pumice cover", "preexisting soil", "bedrock", "scour level"),
  prop_erosion = c("soil movement", "erosion rate", "landslide activity", "sediment runoff", "rill prevalence")
)

# sort property interaction results into the set groups
for (group in names(groups_field_prop)) {
  field_data[[group]] <- check_full_terms(field_data$int_plant_prop, groups_field_prop[[group]])
}

```
```{r upset chart for prop interactions}
# Select only the columns specified in the groups_field_prop list
prop_f_matrix <- field_data %>%
  select(all_of(names(groups_field_prop))) %>%
  mutate(across(everything(), as.integer))  # TRUE/FALSE to 1/0

# Create UpSet plot
upset(prop_f_matrix, sets = c("prop_topo","prop_weather", "prop_size", "prop_seed_src", 
      "prop_disturb_prox", "prop_prior_disturb", "prop_zone", "prop_soil_chem",
      "prop_soil_phys","prop_erosion"), mb.ratio = c(0.55, 0.45), order.by = "freq")
```


```{r print T/F field results}
# Group TF columns
summary_field_columns <- c("veg_trait_TF", "trait_size", "trait_root", "trait_leaf", 
                     "trait_other", "veg_spp_TF", "int_plant_plant_TF", "int_plant_other_TF", "int_plant_prop_TF", 
                     "time_TF", "compare_veg_TF", "seeds_TF", "exotic_TF", "prop_topo", "prop_weather", "prop_size", 
                     "prop_seed_src", "prop_disturb_prox", "prop_prior_disturb", "prop_zone", "prop_soil_chem", 
                     "prop_soil_phys", "prop_erosion")

# Extract relevant columns
field_to_summarize <- field_data[summary_field_columns]

# Count TRUE and FALSE values across all specified columns
true__field_counts <- colSums(field_to_summarize == "TRUE", na.rm = TRUE)
false_field_counts <- colSums(field_to_summarize == "FALSE", na.rm = TRUE)

# Create a summary data frame
summary_field_TF <- data.frame(
  True = true__field_counts,
  False = false_field_counts,
  stringsAsFactors = FALSE
)

# Display the final summary table
print(summary_field_TF)

```
## Specific T/F results

``` {r comparisons & time & seeds results}
# Comparisons
field_data <- field_data %>%
  mutate(compare_veg = str_replace(compare_veg, "TRUE - ", ""))
table(field_data$compare_veg)

# Time
field_data <- field_data %>%
  mutate(time = str_replace(time, "TRUE - ", ""))
table(field_data$time)


#Seeds
field_data <- field_data %>%
  mutate(seeds = str_replace(seeds, "TRUE - ", "")) 

table(field_data$seeds)

```

``` {r comparisons results}
groups_field_compare <- list(
  compare_natural = c("natural", "pre-slip"),
  compare_exp = c("planted", "rehabilitated", "fertilized", "terraced", "fenced",
                  "exp", "reinforced", "barrier", "seeded"),
  compare_other_dist = c("grazed", "logging", "burnt", "flooded", "pyroclastic flow"))

# sort property interaction results into the set groups
for (group in names(groups_field_compare)) {
  field_data[[group]] <- check_partial_terms(field_data$compare_veg, groups_field_compare[[group]])
}

# Select only the columns specified in the groups_field_compare list
field_compare_matrix <- field_data %>%
  select(all_of(names(groups_field_compare))) %>%
  mutate(across(everything(), as.integer))  # TRUE/FALSE to 1/0

# Create UpSet plot
upset(field_compare_matrix, sets = c("compare_natural","compare_exp", "compare_other_dist"), 
      mb.ratio = c(0.55, 0.45), order.by = "freq")

```


## Plot & plotless

``` {r plot & plotless}
#primary survey method
table(field_data$plot_plotless)

#plot size summary
field_data$plot_size <- suppressWarnings(as.numeric(field_data$plot_size))
summary(field_data$plot_size)

#plot size histogram
ggplot(field_data, aes(x = plot_size)) +
  geom_histogram(binwidth = 1, fill = "grey", color = "black", na.rm = TRUE) +
  scale_x_continuous(trans = 'sqrt', breaks = c(100, 400, 900)) +  # Breaks at squared values
  labs(title = "Plot size of Field Surveys",
       x = "Plot size (m2)",
       y = "Studies") +
  theme_minimal()

#plotless methods
field_plotless_methods <- field_data %>%
  mutate(plotless_method = str_replace(plotless_method, "TRUE - ", "")) %>%
  separate_rows(plotless_method, sep = ", ")

table(field_plotless_methods$plotless_method)

```
